function validateInputs(Ip_W, endTime, constants)
% validateInputs Checks simulation inputs for physical validity.

    if ~isscalar(Ip_W) || ~isnumeric(Ip_W) || ~isfinite(Ip_W) || Ip_W < 0
        error('validateInputs:invalidPumpPower', ...
            'Ip_W must be a finite non-negative scalar. Got: %s', mat2str(Ip_W));
    end

    if ~isscalar(endTime) || ~isnumeric(endTime) || ~isfinite(endTime) || endTime <= 0
        error('validateInputs:invalidEndTime', ...
            'endTime must be a finite positive scalar. Got: %s', mat2str(endTime));
    end

    requiredFields = { ...
        'kcr', 'ketu1', 'ketu2', 'tau2', 'tau3', 'tau4', ...
        'ndop', 'sigmaEmission', 'sigmaAbsorption', ...
        'sigmaPumpAbs', 'lambdaPump', 'h', 'c', ...
        'beta43', 'beta42', 'beta32', 'L' ...
    };
    for i = 1:numel(requiredFields)
        if ~isfield(constants, requiredFields{i})
            error('validateInputs:missingField', ...
                'Constants struct missing required field: %s', requiredFields{i});
        end
    end

    positiveFields = { ...
        'kcr', 'ketu1', 'ketu2', 'tau2', 'tau3', 'tau4', ...
        'ndop', 'sigmaEmission', 'sigmaPumpAbs', ...
        'lambdaPump', 'h', 'c', 'L' ...
    };
    for i = 1:numel(positiveFields)
        val = constants.(positiveFields{i});
        if ~isfinite(val) || val <= 0
            error('validateInputs:invalidConstant', ...
                'Constant "%s" must be finite and positive. Got: %g', ...
                positiveFields{i}, val);
        end
    end

    if ~isfinite(constants.sigmaAbsorption) || constants.sigmaAbsorption < 0
        error('validateInputs:invalidConstant', ...
            'sigmaAbsorption must be finite and non-negative. Got: %g', ...
            constants.sigmaAbsorption);
    end

    beta4_sum = constants.beta43 + constants.beta42;
    if beta4_sum > 1
        error('validateInputs:invalidBranching', ...
            'beta43 + beta42 must be <= 1. Got: %g', beta4_sum);
    end
    if constants.beta32 > 1
        error('validateInputs:invalidBranching', ...
            'beta32 must be <= 1. Got: %g', constants.beta32);
    end
    if constants.beta43 < 0 || constants.beta42 < 0 || constants.beta32 < 0
        error('validateInputs:invalidBranching', 'Branching ratios must be non-negative.');
    end
end
